config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "subjects#index"
  get "subjects/explain" => "subjects#explain"
  get 'search', to: 'subjects#search'
  resources :subjects do
    resources :answers
    collection do
      get :search
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :subject

  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :answers, dependent: :destroy


    validates :subject_name, presence: true
    validates :teacher_name, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def create
        @subject = Subject.find(params[:subject_id])
        @subject.answers.create(answer_params)
        redirect_to subject_path(@subject)
    end

    def destroy
        @subject = Subject.find(params[:subject_id])
        @answer = @subject.answers.find(params[:id])
        @answer.destroy
        redirect_to @subject, status: :see_other
    end

    private
    def answer_params
        params.require(:answer).permit(:name, :content)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
    def index
        @subjects = Subject.all
        @q = Subject.ransack(params[:q])
        @users = @q.result(distinct: true)
    end

    def show
        @subject = Subject.find(params[:id])
    end

    def new
        @subject = Subject.new
    end

    def create
        @subject = Subject.new(subject_params)
        if @subject.save
            redirect_to @subject
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def edit
        @subject = Subject.find(params[:id])
    end

    def update
        @subject = Subject.find(params[:id])
        if @subject.update(subject_params)
            redirect_to @subject
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        @subject = Subject.find(params[:id])
        @subject.destroy
        redirect_to subject_path
    end

    def explain
    end

    private
    def subject_params
        params.require(:subject).permit(:subject_name, :teacher_name)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subjects/_form.html.erb
<div>
    <%= link_to 'HOME', subjects_path %>
</div>
<%= form_with model: @subject do |form| %>
    <% if @subject.errors.any? %>
        <div>
            <ul>
                <% @subject.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="create_thread">
        <div>
            <%= form.label :クラス名 %><br>
            <%= form.text_field :subject_name %>
        </div>
        <div>
            <%= form.label :教授名 %><br>
            <%= form.text_field :teacher_name %>
        </div>
        <div>
            <%= form.submit "送信" %>
        </div>
    </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>編集画面</h1>
<%= render partial: 'form' %>

app/views/subjects/explain.html.erb
<h2>ちょっとした掲示板の説明</h2>
<%= link_to 'HOME', subjects_path %>
<ul>
    <li>作成されたスレッドは2時間後に削除されます</li>
    <li>クラス名のリンクを押すことで開くことができます</li>
    <li>編集のリンクではクラス名と教授名の変更が可能です</li>
    <li>書き込みの際、名前を入力しないと"名無し"で書きこまれます</li>
</ul>

app/views/subjects/index.html.erb
<h1>関西学院大学　掲示板</h1>
<div class="explain">
    <%= link_to "ちょっとした掲示板の説明", "/subjects/explain" %>
</div>    

<div class="home_link">
    <%= link_to 'スレッドを立てる', new_subject_path %>
</div>
<div class="search">
    <%= search_form_for @q do |f| %>
        <%= f.label :name_cont, "クラス名検索" %><br>
        <%= f.search_field :subject_name_cont %>
 
        <%= f.submit %>
    <% end %>
</div>

<table>
    <tr>
        <th>クラス名</th>
        <th>教授名</th>
        <th>作成日時</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.subject_name, subject_path(user) %></td>
        <td><%= user.teacher_name %></td>
        <td><%= user.created_at.in_time_zone('Tokyo') %></td>
        <td><%= link_to '編集', edit_subject_path(user) %></td>
        <% if Time.now - user.created_at > 7200 %>
            <% user.destroy %>
        <% end %>
    </tr>
    <% end %>
</table> 

app/views/subjects/new.html.erb
<h1>スレッドを立てる</h1>
<%= render partial: 'form' %>

app/views/subjects/show.html.erb
<h2>
    クラス名: 
    <%= @subject.subject_name %>
</h2>
<h3>
    教授名: 
    <%= @subject.teacher_name %>
</h3>
<div>
    <%= link_to 'HOME', subjects_path %>
</div>

<div>
    <% id = 1 %>
    <% @subject.answers.each do |answer| %>
        <p class="answer_post">
            <%= id %>
            Name:
            <% if answer.name.empty? %>
                名無し
            <% else %>
                <%= answer.name %>
            <% end %>           
            <%= answer.updated_at.in_time_zone('Tokyo') %>
        </p>
        <p>
            <% text = answer.content %>
            <%= safe_join(text.split("\n"), tag(:br)) %>
        </p>
        <% id += 1 %>
    <% end %>
</div>

<h2 class="create_post">投稿作成</h2>
<%= form_with model: [@subject, @subject.answers.build] do |form| %>
    <div>
        <%= form.label :名前 %><br>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :投稿内容 %><br>
        <%= form.text_area :content %>
    </div>
    <div>
        <%= form.submit '送信' %>
    </div>
<% end %>